#!/bin/bash

export COUNT=1

function curl() {
  echo "line $COUNT: curl $0 $@";   \
  command curl  $@ --verbose              \
    | sed -E $'s/}, {/},\\\n    {/g' \
    | sed -E $'s/", "hrefs": /",\\\n"hrefs": /g'    \
    | sed -E $'s/ \[/ \[\\\n    /g'  \
    | sed -E $'s/}\], "/}\],\\\n\],\\\n"/g'         \
    | sed -E $'s/^{"/{\\\n"/g'       \
    | sed -E $'s/"}$/"\\\n}/g'       \
    | sed -E $'s/^/    /g'

    echo ;

    COUNT=$(( COUNT + 1 )) ;
}

# main ------------------------------

# line 1
curl -X GET "http://localhost:5000"

# file open
curl -X GET -H "host:drancom.com" "http://localhost:5000"
curl -X GET -H "host:drancom.com" "http://localhost:5000/datasets"
curl -X GET -H "host:drancom.com" "http://localhost:5000/groups"
curl -X GET -H "host:drancom.com" "http://localhost:5000/datatypes"

curl -X GET -H "host:drancom.com" http://localhost:5000/groups/1fa208c6-aebf-11e6-b761-0242ac140002/links

curl -X GET -H "host:data.drancom.com" http://localhost:5000/groups/1fa208c6-aebf-11e6-b761-0242ac140002/links/data


## data1
#curl -X GET -H "host:data1.drancom.com" "http://localhost:5000/groups"
#curl -X GET -H "host:data1.drancom.com" "http://localhost:5000/groups/3d463b7c-aefb-11e6-bfd9-0242ac140002"
#curl -X GET -H "host:data1.drancom.com" "http://localhost:5000/groups/3d463b7c-aefb-11e6-bfd9-0242ac140002/links"
#
